CREATE TABLE TRANSACTIONS(
	id SMALLINT,
	copyID SMALLINT,
	userID SMALLINT,
	dateBorrowed DATE, 
	dateReturned DATE, 
	dueDate DATE,
	FOREIGN KEY (copyID) REFERENCES COPIES(id),
	FOREIGN KEY (userID) REFERENCES LIBRARY_USER(id) 
);